% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Feb-2024 08:02:43
%  MATLAB version: 9.14.0.2206163 (R2023a)
% -------------------------------------------------------------------
saveVarsMat = load('Activity1.mat');

F1 = saveVarsMat.F1; % <1x1 sym> unsupported class

F2 = saveVarsMat.F2; % <1x1 sym> unsupported class

F3 = saveVarsMat.F3; % <1x1 sym> unsupported class

F4 = saveVarsMat.F4; % <1x1 sym> unsupported class

F5 = saveVarsMat.F5; % <1x1 sym> unsupported class

F6 = saveVarsMat.F6; % <1x1 sym> unsupported class

f1 = saveVarsMat.f1; % <1x1 sym> unsupported class

f2 = saveVarsMat.f2; % <1x1 sym> unsupported class

f3 = saveVarsMat.f3; % <1x1 sym> unsupported class

f4 = saveVarsMat.f4; % <1x1 sym> unsupported class

f5 = saveVarsMat.f5; % <1x1 sym> unsupported class

f6 = saveVarsMat.f6; % <1x1 sym> unsupported class

s = saveVarsMat.s; % <1x1 sym> unsupported class

t = saveVarsMat.t; % <1x1 sym> unsupported class

clear saveVarsMat;
